Repository Ayush7614/Daily-Coding-DS-ALGO-Practice, pull requests merged in 2021-08, with the labels that each got.

#2304 Designer PDF viewer- HackerRank
  Hackerank/C++/Designer PDF Viewer.cpp
Labels: LGMSOC21, 🟩 Level1

#2287 Added "Chess Format" problem of codechef
  Codechef/C++/Chess Format (CHSFORMT).cpp
Labels: LGMSOC21, 🟩 Level1

#2288 Added "Food Chain" problem of codechef
  Codechef/C++/Food Chain (FODCHAIN).cpp
Labels: LGMSOC21, 🟩 Level1

#2320 Added "Chef In Infinite Plane" problem of codechef
  Codechef/C++/Chef In Infinite Plane (CHFPLN).cpp
Labels: LGMSOC21, 🟩 Level1

#2322 Added "Red Alert" problem of codechef
  Codechef/C++/Red Alert (REDALERT).cpp
Labels: LGMSOC21, 🟩 Level1

#2323 Added "Beautiful Pairs" problem of codechef
  Codechef/C++/Beautiful Pairs (BUTYPAIR).cpp
Labels: LGMSOC21, 🟩 Level1

#2327 Added SubArrayWithSum.cpp
  Data Structures/Array/C++/SubArrayWithSum.cpp
Labels: LGMSOC21, 🟩 Level1

#2311 Strong password
  Hackerank/Java/Strong-password.java
Labels: LGMSOC21, 🟩 Level1

#2310 added code for mod-equality in c++
  Codechef/C++/mod-equality.cpp
Labels: LGMSOC21, 🟨 Level2

#2336 C++ Solution for "Letter Combinations of a Phone Number" under LGMSOC21
  Leetcode/C++/Letter_Combinations_Phone_Number.cpp
Labels: LGMSOC21, 🟩 Level1

#2342 Java-Solution Chess Format
  Codechef/Java/Chess Format.java
Labels: LGMSOC21, 🟩 Level1

#2343 Java-Solution Food Chain
  Codechef/Java/Food Chain.java
Labels: LGMSOC21, 🟩 Level1

#2354 Added Solution of ATM(Codechef) in Java under LGMSOC'21
  Codechef/Java/atm.java
Labels: LGMSOC21, 🟩 Level1

#2353 Added Solution of studying Alphabet (Codechef) in Java Under LGMSOC'21
  Codechef/Java/studyingAlphabet.java
Labels: LGMSOC21, 🟩 Level1

#2363 Added solution of Multiply Strings(Leetcode) in Python Under LGMSoc'21
  Leetcode/Python/multiplyStrings.py
Labels: 🟪 Level0

#2365 Create print_the_subset.java
  Data Structures/print_the_subset.java
Labels: LGMSOC21, 🟩 Level1

#2360 Added Solution of The Lead Game(Codechef) in Java.
  Codechef/Java/The_Lead_Game.java
Labels: LGMSOC21, 🟩 Level1

#2359 Code For Display The number In word Format
  Gfg/DisplayNumberInWord.cpp
Labels: LGMSOC21, 🟨 Level2

#2366 Sort an array containing only 0,1,2's
  Gfg/Java/Sort_012s.java
Labels: LGMSOC21, 🟩 Level1

#2376 Create Shortest Distance in Weighted graph using BFS
  Data Structures/Shortest Distance in Weighted graph using BFS
Labels: accepted, open source, approved
