Repository Ayush7614/Daily-Coding-DS-ALGO-Practice, pull requests merged in 2021-07, with the labels that each got.

#988 Josephus problem added using C++
  Leetcode/josephus_problem_recursion.cpp
Labels: LGMSOC21, 🟩 Level1

#1483 Pascal Triangle.c
  Leetcode/Pascal Triangle.c
Labels: LGMSOC21, 🟨 Level2

#1543 Sleep Cycle (Codechef Starters)
  Codeforces/Sleep_Cycle.java
Labels: LGMSOC21, 🟩 Level1

#1570 Added All Priority Queue Operations using Array and Linked List
  Data Structures/Priority_Queue.cpp
Labels: LGMSOC21, 🟥 Level4

#1565 Added odd even segregate code
  Data Structures/odd_even_seggregate.c
Labels: LGMSOC21, 🟩 Level1

#1572 Added Code for Reverse Linked List Using Stack
  Data Structures/Reverse_ll_using_Stack.cpp
Labels: LGMSOC21, 🟨 Level2

#1574 Added all operation of Binary Search Tree
  Data Structures/Binary_Search_Tree.cpp
Labels: LGMSOC21, 🟧 Level3

#1592 Added unlucky ticket in python.
  Codeforces/Unlucky_ticket.py
Labels: LGMSOC21, 🟨 Level2

#1576 Klee Algorithm added
  Data Structures/Klee's Algorithm.cpp
Labels: LGMSOC21, 🟨 Level2

#1109 Fenced Matrix using Python
  Data Structures/fenced_matrix.py
Labels: LGMSOC21, 🟩 Level1

#1583 FloydWarshall in C++
  Algorithms/Dynamic Problems/FloydWarshall.cpp
Labels: LGMSOC21, 🟨 Level2

#1584 FloydWarshall in Java
  Algorithms/Dynamic Problems/FloydWarshall.java
Labels: LGMSOC21, 🟨 Level2

#1585 FloydWarshall in python 3
  Algorithms/Dynamic Problems/FloydWarshall.py
Labels: LGMSOC21, 🟨 Level2

#1588 Added solution for Indian Coin Change Problem in Python
  Codeforces/Indian Coin Change.py
Labels: LGMSOC21, 🟩 Level1

#1597 Ugly Number
  Gfg/uglynum.cpp
Labels: LGMSOC21, 🟩 Level1

#1559 Update README.md
  README.md
Labels: LGMSOC21, 🟩 Level1

#1619 Added code for Celebrity problem (GFG)
  Gfg/celebrity_problem.cpp
Labels: LGMSOC21, 🟧 Level3

#1636 Create Palindromic partitioning.cpp
  Gfg/Palindromic partitioning.cpp
Labels: LGMSOC21, 🟨 Level2

#1642 Added shortest supersequence
  Leetcode/shortest_supersequence.py
Labels: LGMSOC21, 🟩 Level1

#1645 added the solution for finding the range of array in C language for issue no. #1329
  Data Structures/rangeminmax.c
Labels: LGMSOC21, 🟨 Level2

#1651 Find n in array of size m
  Gfg/Find_n_in_array.py
Labels: LGMSOC21, 🟩 Level1

#1637 Added New Problem - Trapping Rain Water
  Leetcode/trappingRainWater.cpp
Labels: LGMSOC21, 🟨 Level2

#1696 Relativity (July Long Challenge)
  Codechef/Relativity.java
Labels: LGMSOC21, 🟩 Level1

#1674 Peak element code added
  Gfg/peak_element.cpp
Labels: LGMSOC21, 🟩 Level1

#1697 Code added for Minimize the Heights II
  Gfg/minimize_the_heights.cpp
Labels: LGMSOC21, 🟧 Level3

#1707 Added Problem Permutations
  Leetcode/permutations.cpp
Labels: LGMSOC21, 🟧 Level3

#1714 Maximum perfect number code added
  Algorithms/perfect_no.cpp
Labels: LGMSOC21, 🟨 Level2

#1644 Added Cpp Solution to Majority Element
  Leetcode/Majority Element.cpp
Labels: LGMSOC21, 🟧 Level3

#1734 Solution for "Add Binary" on LeetCode for Issue #1725
  Leetcode/AddBinary.cpp
Labels: LGMSOC21, 🟩 Level1

#1531 Adding Problem 1526B of codeforces in JAVA
  Codeforces/I_Hate_1111(Problem1526B).java
Labels: LGMSOC21, 🟨 Level2

#1738 Added postorder traversal in python
  Data Structures/Tree/postorder_traversal.py
Labels: LGMSOC21, 🟨 Level2

#1557 Added problem B of AtCoder DP
  Algorithms/Dynamic Problems/B Frog2.cpp
Labels: LGMSOC21, 🟨 Level2

#1604 First missing positive number in unsorted array. (in java)
  Leetcode/First_missing_positive_num.java
Labels: LGMSOC21, 🟨 Level2

#1749 added solution for issue number #1331 in C language
  Data Structures/npresentornot.c
Labels: LGMSOC21, 🟨 Level2

#1761 Solution for Fixed Parities
  Data Structures/fixed_parities.cpp
Labels: LGMSOC21, 🟩 Level1

#1765 Solution for "Union And Intersection" And "Grid And Phrase"
  Data Structures/union_and_intersection.cpp
Labels: LGMSOC21, 🟩 Level1

#1627 add Police and Thieve.cpp
  Algorithms/Greedy Algorithms/Police and Thieve.cpp
  Leetcode/maximum rectangular area in histogram.cpp
Labels: LGMSOC21, 🟨 Level2

#1755 Added Sieve of Eratosthenes method solution
  Gfg/Sieve of Eratosthenes.cpp
Labels: LGMSOC21, 🟨 Level2

#1772 Create Taylor_series.cpp
  Algorithms/Greedy Algorithms/Taylor_series.cpp
Labels: LGMSOC21, 🟨 Level2

#1338 Longest Consecutive Sequence using Python
  Algorithms/Longest_Consecutive_Sequence.py
Labels: LGMSOC21, 🟩 Level1

#1605 Create RodCutting.java
  Leetcode/RodCutting.java
Labels: LGMSOC21, 🟩 Level1

#1606 Added "Chess Match" Problem of June CodeChef Starters in c++
  Codechef/Chess Match (BLITZ3_2).cpp
Labels: LGMSOC21, 🟩 Level1

#1629 Added "Total Correct Submissions" Problem of June CodeChef Starters in c++
  Codechef/Total Correct Submissions (TOTCRT).cpp
Labels: LGMSOC21, 🟩 Level1

#1632 Added Solution for Remove Duplicate Element from Unsorted Linked List
  Gfg/Remove_Duplicate_Elements_from_Unsorted_LL.java
Labels: LGMSOC21, 🟨 Level2

#1634 Added "Sleep Cycle" Problem of June CodeChef Starters in C++
  Codechef/Sleep Cycle (SLPCYCLE).cpp
Labels: LGMSOC21, 🟩 Level1

#1650 Spell error under LGM SOC 2021
  README.md
Labels: LGMSOC21, 🟪 Level0

#1652 Added Shower Line solution in Codeforces
  Codeforces/Shower_Line.cpp
Labels: LGMSOC21, 🟩 Level1

#1654 Create Detect Cycle in Linklist.cpp
  Detect Cycle in Linklist.cpp
Labels: LGMSOC21, 🟨 Level2

#1808 Added sieve of eratosthenes in python
  Gfg/sieve_of_eratosthenes.py
Labels: LGMSOC21, 🟨 Level2

#1660 Center of Star Graph Added
  Data Structures/Center_Of_Star_Graph.cpp
Labels: LGMSOC21, 🟨 Level2

#1661 Reverse Linked List Using Stack.cpp
  Data Structures/Reverse a link list using stack.cpp
Labels: LGMSOC21, 🟨 Level2

#1663 Added Solution of Day-of-the-programmer in java under LGMSOC'21
  Hackerank/Day-of-the-programmer.java
Labels: LGMSOC21, 🟨 Level2

#1664 Added 1-based index of lucky number.cpp file
  Codeforces/1-based index of lucky number.cpp
Labels: LGMSOC21, 🟩 Level1

#1673 Added "Multiple of 3" Problem of Complexity Analysis + Basics Warm Up ( Codechef )
  Codechef/Multiple of 3 (MULTHREE).cpp
Labels: LGMSOC21, 🟨 Level2

#1657 Added Regular_Expression_Matching(hard) solution in LeetCode
  Leetcode/Regular_Expression_Matching(hard).cpp
Labels: LGMSOC21, 🟨 Level2

#1675 unpleasant ones code added
  Codechef/unpleasant_ones.cpp
Labels: LGMSOC21, 🟨 Level2

#1677 Create Validate_IP.cpp
  Gfg/Validate_IP.cpp
Labels: LGMSOC21, 🟧 Level3

#1773 Added Solution of Codeforces Round 729 Problem A
  Codeforces/1542A_Odd_Set.cpp
Labels: LGMSOC21, 🟩 Level1

#1413 Added Tree_Traversal.cpp under Data Structures
  Data Structures/Tree/Tree_Traversal.cpp
Labels: LGMSOC21, 🟧 Level3

#1630 Ugly numbers algorithm added
  Gfg/ugly_num.py
Labels: LGMSOC21, 🟩 Level1

#1679 Prisoners Escape
  Algorithms/Graphs/Prisoners_escape.cpp
Labels: LGMSOC21, 🟨 Level2

#1722 The Skyline problem from leetcode
  Leetcode/SkyLine.cpp
Labels: LGMSOC21, 🟧 Level3

#1723 added Dense Graph (DENSEGRP) of Codechef in C++ under LGMSOC'21
  Codechef/Dense Graph (DENSEGRP).cpp
Labels: LGMSOC21, 🟨 Level2

#1671 Unpleasant ones (Codechef Lunchtime)
  Codechef/Unpleasant Ones.java
Labels: LGMSOC21, 🟨 Level2

#1728 Added Rabin Karp Algorithm in Algorithm
  Algorithms/rabin_karp_algorithm.py
Labels: LGMSOC21, 🟨 Level2

#1729 Added "ICPC Balloons" Problem of June Cook-Off 2021 Division 3 (Codechef)
  Codechef/ICPC Balloons (BALLOON).cpp
Labels: LGMSOC21, 🟨 Level2

#1730 Issue 1573-Matrix Chain Multiplication - DP Algorithm
  Algorithms/MCM_Memoisation.cpp
Labels: LGMSOC21, 🟨 Level2

#1731 Added "The Wave" problem of June Cook-off Codechef
  Codechef/The Wave (WAV2).cpp
Labels: LGMSOC21, 🟨 Level2

#1832 Added last index of an array in python.
  Gfg/last_index_of_array.py
Labels: LGMSOC21, 🟨 Level2

#1775 Geek_onacci.cpp
  Gfg/Geek_onacci.cpp
Labels: LGMSOC21, 🟨 Level2

#1718 added total_correct_submissions
  Codechef/Total_Correct_Submissions.cpp
Labels: LGMSOC21, 🟩 Level1

#1869 Code Added for count and say
  Leetcode/count_and_say.cpp
Labels: LGMSOC21, 🟨 Level2

#1857 Fixes #1806 and #1839
  Leetcode/Deepest Leaves Sum.cpp
  Leetcode/remove nth node from end of list.cpp
Labels: LGMSOC21, 🟨 Level2

#1842 Create k_arrayheap.cpp
  Algorithms/Dynamic Problems/k_arrayheap.cpp
Labels: LGMSOC21, 🟨 Level2

#1072 Transitive_Closure_of_Graph.cpp
  Gfg/Transitive_Closure_of_Graph.cpp
Labels: LGMSOC21, 🟧 Level3

#1649 Created Combination Sum.cpp
  Leetcode/Combination Sum.cpp
Labels: LGMSOC21, 🟩 Level1

#1658 Solution of Skyline Problem in Python
  Leetcode/skyline Problem.py
Labels: LGMSOC21, 🟧 Level3

#1672 Solution of Lucky Alive Person in Python
  Gfg/Lucky alive person.py
Labels: LGMSOC21, 🟧 Level3

#1733 Added Bitonic point
  Gfg/Bitonic_Point.cpp
Labels: LGMSOC21, 🟨 Level2

#1736 Cpp solution to issue 1331
  Gfg/Find_n_in_array.cpp
Labels: LGMSOC21, 🟩 Level1

#1740 Java solution to issue 1377
  Codeforces/ChatRoom.java
Labels: LGMSOC21, 🟨 Level2

#1757 Solution of Valid Mountain Problem in python
  Leetcode/Valid_Mountain_Problem.py
Labels: LGMSOC21, 🟨 Level2

#1762 Added Bucket Sort in JAVA
  Algorithms/Bucket_Sort_JAVA.java
Labels: LGMSOC21, 🟩 Level1

#1769 Solution of Next greater element using stack
  Gfg/Next Greater Element.cpp
Labels: LGMSOC21, 🟨 Level2

#1779 Create Job Sequencing Problem.cpp
  Gfg/Job Sequencing Problem.cpp
Labels: LGMSOC21, 🟩 Level1

#1781 C++ solution to issue 1445
  Hackerank/Day_Of_a_Programmer.cpp
Labels: LGMSOC21, 🟨 Level2

#1786 linkedlist in java
  Algorithms/LinkedList/linkedlist.java
Labels: LGMSOC21, 🟨 Level2

#1884 Solution for move all negative numbers at beginning
  Data Structures/move_all_negative.cpp
Labels: LGMSOC21, 🟧 Level3

#1892 Code added for Word Wrap
  Gfg/word_wrap.cpp
Labels: LGMSOC21, 🟧 Level3

#1878 Fixes #1858 and #1859
  Leetcode/Fruits into Baskets.cpp
  Leetcode/Permutation in string.cpp
Labels: LGMSOC21, 🟨 Level2

#1902 added sum replacement
  Data Structures/Tree/sum_replacement.cpp
Labels: LGMSOC21, 🟨 Level2

#1737 1621 egg dropping puzzle cpp
  Gfg/Egg_Dropping_Puzzle.cpp
Labels: LGMSOC21, 🟨 Level2

#1788 "Added code for StringtoInteger(atoi) in python"
  Leetcode/StringtoInteger.py
Labels: LGMSOC21, 🟨 Level2

#1789 Added code for kth max min in java
  Data Structures/kthmaxmin.java
Labels: LGMSOC21, 🟩 Level1

#1796 Added Wave Array
  Gfg/wave_array.java
Labels: LGMSOC21, 🟨 Level2

#1799 Add-1-to-a-number-represented-as-linked-list
  Gfg/Add-1-to-a-number-represented-as-linked-list.java
Labels: LGMSOC21, 🟨 Level2

#1922 Fixes #1908
  Leetcode/Longest common prefix.cpp
  Leetcode/longest increasing subsequence.cpp
Labels: LGMSOC21, 🟧 Level3

#1662 Added solution of contains-duplicate (Leetcode) in Java.
  Leetcode/contains-duplicate.java
Labels: LGMSOC21, 🟨 Level2

#1809 Issue 1025 - Shortest Common Supersequence
  Leetcode/ShortestCommonSupersequence.cpp
Labels: LGMSOC21, 🟨 Level2

#1812 Create minimum-swaps-to-group-all-1s-together.cpp
  Gfg/minimum-swaps-to-group-all-1s-together.cpp
Labels: LGMSOC21, 🟩 Level1

#1819 Maximum XOR of Two Array added
  Data Structures/Max_XOR_of_Two_Array.cpp
Labels: LGMSOC21, 🟨 Level2

#1844 Added Forming a Magic Square problem code to Hackerranck folder
  Hackerank/MagicSquare.java
Labels: LGMSOC21, 🟩 Level1

#1845 Solution to Dividing Stamps question
  Codechef/dividingStamps.c
Labels: LGMSOC21, 🟩 Level1

#1846 I have solve BinarySearch using JAVA.
  Data Structures/BinarySearch.java
Labels: LGMSOC21, 🟨 Level2

#1848 [cryptography]Hill Cipher
  Gfg/Main.java
Labels: LGMSOC21, 🟧 Level3

#1802 Adding Doubly-Linked-List2.cpp
  Data Structures/LinkedList/C++/Doubly-Linked-List2.cpp
Labels: LGMSOC21, 🟧 Level3

#1853 Added 'The Wave' problem of June Cook-off challenge in java
  Codechef/TheWave.java
Labels: LGMSOC21, 🟨 Level2

#1861 Added Sudoku Solver in LeetCode
  Leetcode/Sudoku_Solver.cpp
Labels: LGMSOC21, 🟧 Level3

#1954 Added all indices of a number in array.
  Gfg/All_indices.py
Labels: LGMSOC21, 🟨 Level2

#1961 Duplicate subtree in Binary Tree
  Gfg/C++/Duplicate subtree in Binary Tree.cpp
  Leetcode/C++/maximum rectangular area in histogram.cpp
Labels: LGMSOC21, 🟨 Level2

#1988 Normal BST to Balanced BST
  Gfg/C++/normal_BST_to_Balanced_BST.cpp
Labels: LGMSOC21, 🟩 Level1

#1706 1628 merge k sorted linked list python code
  Data Structures/Merge k sorted linkedlist.py
Labels: LGMSOC21, 🟨 Level2

#1732 1618 majority element pythoncode
  Data Structures/MajorityElement.py
Labels: LGMSOC21, 🟩 Level1

#1810 added Zero problem GFG coding contest 2021
  Gfg/zero.cpp
Labels: LGMSOC21, 🟩 Level1

#1840 #1795 Word Ladder - II
  Leetcode/WordLadder-II.py
Labels: LGMSOC21, 🟨 Level2

#1880 Added 'Flappy Bird' problem code in java
  Codechef/FlappyBird.java
Labels: LGMSOC21, 🟨 Level2

#1888 Added code for Indian coin change problem
  Data Structures/Indiancoinchange.c
Labels: LGMSOC21, 🟩 Level1

#1889 Added Solution of Pow(x,n) (Leetcode) in Python
  Leetcode/Pow(x,n).py
Labels: LGMSOC21, 🟩 Level1

#1890 Code added for Median of Two Sorted Arrays
  Leetcode/Median of Two Sorted Arrays.java
Labels: LGMSOC21, 🟨 Level2

#1894 Median of 2 sorted array #340
  Gfg/MedianOfTwoSortedArrayJava.java
Labels: LGMSOC21, 🟨 Level2

#1897 added file for finding third largest element in array
  Gfg/thirdlargestElement.cpp
Labels: LGMSOC21, 🟨 Level2

#2020 Rotten Oranges
  Gfg/C++/Rotten Oranges.cpp
Labels: LGMSOC21, 🟩 Level1

#2033 Count squares
  Gfg/C++/count_squares.cpp
Labels: LGMSOC21, 🟩 Level1

#2025 Added code for serialize and deserialize bt
  Leetcode/C++/Serialize and Deserialize Binary tree.cpp
Labels: LGMSOC21, 🟩 Level1

#2029 Sets-STL HackerRank
  Hackerank/C++/Sets-STL.cpp
Labels: LGMSOC21, 🟩 Level1

#2031 Maps-STL HackerRank
  Hackerank/C++/Maps-STL.cpp
Labels: LGMSOC21, 🟩 Level1

#1864 issue number 1449
  Gfg/add two number by linked list.java
Labels: LGMSOC21, 🟨 Level2

#1865 sort012 in java issue 1768
  Algorithms/Searching and Sorting/sort012.java
Labels: LGMSOC21, 🟩 Level1

#1891 Added code for issue 1647
  Gfg/RotateALinkedList.cpp
Labels: LGMSOC21, 🟨 Level2

#1912 Added Negative weight cycle problem code
  Gfg/Negative_weight_cycle.cpp
Labels: LGMSOC21, 🟨 Level2

#1919 Check if Sentence is Pangram.cpp
  Leetcode/Check if Sentence is Pangram.cpp
Labels: LGMSOC21, 🟩 Level1

#1925 Added Solution of check-if-the-sentence-is-pangram in java under LGMSOC'21
  Leetcode/check-if-the-sentence-is-pangram.java
Labels: LGMSOC21, 🟩 Level1

#1933 issue #1622 : added ReverSort.java
  codejam/Java/ReverSort.java
Labels: LGMSOC21, 🟨 Level2

#1953 C++ Recursive Solution to "Swap Nodes in Pairs" on LeetCode under LGMSOC21
  Leetcode/C++/SwapNodesInPairs.cpp
Labels: LGMSOC21, 🟩 Level1

#2077 Adding the N_Slimes solution in the Atcoder folder
  Atcoder dp/N - Slimes.cpp
Labels: LGMSOC21, 🟩 Level1

#2074 Fair Playoff Codeforces Solution
  Codeforces/C++/Fair Playoff.cpp
Labels: LGMSOC21, 🟩 Level1

#2097 Calculate nCr
  Gfg/C++/Calculate_nCr.cpp
  Gfg/C++/calculate_nPr.cpp
Labels: LGMSOC21, 🟪 Level0

#1860 merge request for issue 1548
  Leetcode/Check If Two String Arrays are Equivalent.java
Labels: LGMSOC21, 🟨 Level2

#1923 merge request for issue #1474
  Gfg/maximum xor.java
Labels: LGMSOC21, 🟨 Level2

#2075 Updated Java-Solution Delete Node in Linked list
  Leetcode/Java/Delete Node in a Linked List.java
Labels: LGMSOC21, 🟨 Level2

#1937 Added Solution of Pair Programming Problem of Codeforces
  Codeforces/1547_C_Pair_Programming.cpp
Labels: LGMSOC21, 🟨 Level2

#1938 Added JohnsonAlgorithm.cpp
  Algorithms/JohnsonAlgorithm.cpp
Labels: LGMSOC21, 🟧 Level3

#1942 operation in singly,doubly,circular llin java for issue number #1416
  Algorithms/LinkedList/circularll.java
  Algorithms/LinkedList/doublyll.java
  Algorithms/LinkedList/singlyll.java
Labels: LGMSOC21, 🟨 Level2

#1963 Added Problem Best Time to buy and sell stocks - III
  Leetcode/C++/Best-time-to-buy-and-sell-stocks-III.cpp
Labels: LGMSOC21, 🟨 Level2

#1969 Added Java-Solution Maximum Length of Repeated Subarray
  Leetcode/Java/Maximum Length of Repeated Subarray.java
Labels: LGMSOC21, 🟩 Level1

#2142 Added "Maximum Production" problem of codechef July Long Challenge
  Codechef/C++/Maximum Production (EITA).cpp
Labels: LGMSOC21, 🟪 Level0

#2011 Java-Solution Swap Nodes in Pairs
  Leetcode/Java/Swap Nodes in Pairs.java
Labels: LGMSOC21, 🟩 Level1

#2063 Added Code for constructing binary tree from preorder and inorder in java Issue 1344
  Leetcode/Java/BinaryTreeFromPreorderAndInorder.java
Labels: LGMSOC21, 🟨 Level2

#2086 Added Custom Sort String problem code
  Leetcode/Java/CustomSortString.java
Labels: LGMSOC21, 🟩 Level1

#2148 Added Merge two sorted LL in Gfg/java folder
  Gfg/Java/Merge_two_sorted_LL.java
Labels: LGMSOC21, 🟨 Level2
