Repository Ayush7614/Daily-Coding-DS-ALGO-Practice, pull requests merged in 2021-10, with the labels that each got.

#2403 Create cqxymcountpermutations.cpp
  Codeforces/Round 745/cqxymcountpermutations.cpp
Labels: accepted, open source, approved, hacktoberfest 21, hacktoberfest-accepted

#2384 Solved issue no #2373 . (Codeforces)112A petya and string #2373 Petya and strings problem solution in c .
  Codeforces/C/petya_and_strings.c
Labels: accepted, open source, approved, hacktoberfest 21, hacktoberfest-accepted

#2405 Partition to K Equal Sum Subsets
  Leetcode/C++/PartitionToKsubset.cpp
Labels: good first issue, hacktoberfest 21, hacktoberfest-accepted

#2423 Create Merge k Sorted Arrays
  Gfg/C++/Merge k Sorted Arrays.cpp
Labels: open source, hacktoberfest 21, hacktoberfest-accepted

#2421 Added count nodes
  Data Structures/Tree/C++/countNodes.cpp
Labels: accepted, open source, approved, hacktoberfest 21, hacktoberfest-accepted

#2416 Sum of Left Leaves
  Data Structures/Tree/Sum of left leaves.cpp
Labels: accepted, open source, approved, hacktoberfest 21, hacktoberfest-accepted

#2442 Added count Nodes greater than X
  Data Structures/Tree/C++/countNodesgreaterthanX.cpp
Labels: open source, hacktoberfest 21, hacktoberfest-accepted

#2443 Add questions
  Codeforces/C++/B_Borze.cpp
  Codeforces/C++/B_Drinks.cpp
  Codeforces/C++/D. Same Differences.cpp
Labels: open source, hacktoberfest 21, hacktoberfest-accepted

#2458 Create rotate matrix.cpp
  Gfg/C++/rotate matrix.cpp
Labels: accepted, open source, approved, hacktoberfest 21, hacktoberfest-accepted

#2459 Create rotate matrix.java
  Gfg/Java/rotate matrix.java
Labels: accepted, open source, approved, hacktoberfest 21, hacktoberfest-accepted

#2464 PAIR OF TOPICS.
  Codeforces/C++/PAIR OF TOPICS.CPP
Labels: accepted, open source, approved, hacktoberfest 21, hacktoberfest-accepted

#2449 Added Minimum Size Subarray Sum
  Leetcode/C++/Minimum Size Subarray Sum.cpp
Labels: open source, hacktoberfest 21, hacktoberfest-accepted
