Repository Ayush7614/Daily-Coding-DS-ALGO-Practice, pull requests merged in 2021-06, with the labels that each got.

#112 Void commit
  Algorithms/binary_recursive_search.cpp
Labels: bug, review, under-review

#155 Sorting Algorithm- Topological Sort
  Algorithms/Topological_sort.cpp
Labels: LGM-SOC'21, Level2

#157 new_password_codeforces #153
  Codeforces/new_password_codeforces.cpp
Labels: LGM-SOC'21, Level1

#166 added code for maximum of window size k problem
  Gfg/max_of_size_k_window_using _deque.cpp
Labels: LGM-SOC'21, Level2

#170 Added Count occurences of an element in a sorted array using Binary S…
  Hackerank/Count Occurences Sorted Array BS.cpp
Labels: LGM-SOC'21, Level1

#228 Added Solution for NQueens Permutation and Combination Genrator
  Algorithms/Backtracking/nQueensPermutationCombination.java
Labels: LGM-SOC'21, Level2

#236 Create n-queen problem.cpp
  Algorithms/Backtracking/n-queen.cpp
Labels: LGM-SOC'21, Level2

#240 Rat in a Maze
  Algorithms/Backtracking/Rat in  a Maze.cpp
Labels: LGM-SOC'21, Level1

#266 Added solution to Space Arrays #244
  Codechef/SpaceArrays.java
Labels: LGMSOC21, 🟨 Level2

#275 Create Spiral order Matrix
  Data Structures/Spiral Order Matrix.cpp
Labels: LGMSOC21, 🟨 Level2

#279 Issue no : #105, Adding string_tokenizer file
  Data Structures/string_tokenizer.cpp
Labels: LGMSOC21, 🟨 Level2

#283 Pattern23(codechef)
  Codechef/pattern_codechef.py
Labels: LGMSOC21, 🟨 Level2

#284 Added solution of Next Greater Element in Java
  Gfg/Next_greater_Element.java
Labels: LGMSOC21, 🟨 Level2

#420 added trapping rainwater in python
  Gfg/trapping_rainwater.py
Labels: LGMSOC21, 🟨 Level2

#287 added Ternary search
  Algorithms/Searching and Sorting/Ternary_search.cpp
Labels: LGMSOC21, 🟨 Level2

#289 Added the C++ code for Union of two sorted arrays .
  union of two sorted arrays.cpp
Labels: LGMSOC21, 🟩 Level1

#291 Added the code of Spiral Display in Gfg implement in Java
  Gfg/SpiralDisplay.java
Labels: LGMSOC21, 🟨 Level2

#294 Added Pairs.java
  Hackerank/Pairs.java
Labels: LGMSOC21, 🟨 Level2

#263 Created array rotation by K element solution in c++ under Data structure folder for issue #167 assigned to me
  Hackerank/Array_rotation_by_K_elemnt.cpp
  Hackerank/Array_rotation_by_K_elemnt.exe
Labels: LGMSOC21, 🟨 Level2

#308 Add Shell_sort.py
  Algorithms/Searching and Sorting/Shell_sort.py
Labels: LGMSOC21, 🟨 Level2

#387 Palindromic Partition #384
  Algorithms/Palindromic_Partitions.cpp
Labels: LGMSOC21, 🟨 Level2

#348 Create Flatten_a_linked_list.cpp
  Gfg/Flatten_a_linked_list.cpp
  Gfg/isomorphic_strings.cpp
Labels: LGMSOC21, 🟨 Level2

#499 Create Generic Swaps Using Templates
  Data Structures/Generic Swaps Using Templates
Labels: LGMSOC21, 🟨 Level2

#466 Implementation of Russian Peasant Multiplication algorithm in C++
  Algorithms/Russian_Peasant_Algorithm.cpp
Labels: LGMSOC21, 🟧 Level3

#369 Add Seive Of Eratosthenes in Java
  Data Structures/SeiveOfEratosthenes.java
Labels: LGMSOC21, 🟨 Level2

#412 Add Comb Sort
  Algorithms/comb_sort.cpp
Labels: LGMSOC21, 🟨 Level2

#402 Add Circle Sort in C++
  Algorithms/circle_sort.cpp
Labels: LGMSOC21, 🟨 Level2

#347 Create Binary_Tree_Symmetric_or_not.cpp
  Data Structures/Binary_Tree_Symmetric_or_not.cpp
Labels: LGMSOC21, 🟨 Level2

#296 Intersection of Sorted Array
  Data Structures/intersection.java
Labels: LGMSOC21, 🟩 Level1

#454 Implementation of Sieve algorithm in C
  Algorithms/Sieve of Eratosthenes.c
Labels: LGMSOC21, 🟨 Level2

#320 Added code to maximize the sum of selected numbers from an array
  Gfg/Maximise sum in array.cpp
Labels: LGMSOC21, 🟨 Level2

#482 Maximize the sum (java code)
  Gfg/MaximizeSum.java
Labels: LGMSOC21, 🟩 Level1

#510 Addition of Capacity_To_Ship_Packages.java problem under Leetcode
  Leetcode/Capacity_To_Ship_Packages.java
Labels: LGMSOC21, 🟩 Level1

#281 Create Linked List in C++
  Data Structures/LinkedList.cpp
Labels: LGMSOC21, 🟩 Level1

#327 Infix to postfix expression conversion
  Data Structures/Infix_to_postfix.cpp
Labels: LGMSOC21, 🟨 Level2

#331 Balanced Rating Changes question on codeforces #273
  Codeforces/Balanced_Rating_Changes._codeforces.cpp
Labels: LGMSOC21, 🟨 Level2

#337 issue-165 resolved
  Gfg/Allocate_minimum_number_of_pages.cpp
Labels: LGMSOC21, 🟨 Level2

#346 Create Trapping Rain Water.cpp
  Gfg/Trapping Rain Water.cpp
Labels: LGMSOC21, 🟨 Level2

#295 #171 Infix to postfix
  Data Structures/Infix to Postfix Using Stack in C.c
Labels: LGMSOC21, 🟨 Level2

#355 Added the code for Subset Sum problem
  Gfg/Subset Sum Prob.cpp
Labels: LGMSOC21, 🟧 Level3

#360 #290 Minimum No of Swaps
  Minimum_swaps_required.cpp
Labels: LGMSOC21, 🟨 Level2

#365 Created solution to problem Lucky Sum of Digits
  Codeforces/Q1_Lucky_sum_of_digits.cpp
Labels: LGMSOC21, 🟨 Level2

#366 Issue #326
  Gfg/maximum_sum_circular_array.cpp
Labels: LGMSOC21, 🟨 Level2

#371 Create find_missing_and_repeating.cpp
  Gfg/find_missing_and_repeating.cpp
Labels: LGMSOC21, 🟨 Level2

#375 Create longest_subarray_with_atmost_k_even_elements.cpp
  Gfg/longest_subarray_with_atmost_k_even_elements.cpp
Labels: LGMSOC21, 🟨 Level2

#377 Create merge_without_extra_space.cpp
  Gfg/merge_without_extra_space.cpp
Labels: LGMSOC21, 🟩 Level1

#373 Added Maximum Sum Answer
  Algorithms/Greedy Algorithms/Maximum sum removing k numbers.cpp
Labels: LGMSOC21, 🟨 Level2

#379 Create median_of_two_sorted_arrays.cpp
  Gfg/median_of_two_sorted_arrays.cpp
Labels: LGMSOC21, 🟨 Level2

#519 Create Adjacent Difference Algo
  Algorithms/Adjacent Difference Algo
Labels: LGMSOC21, 🟨 Level2

#449 Added reverse array in cpp
  Gfg/Reversearray.cpp
Labels: LGMSOC21, 🟩 Level1

#542 Siddhi 244 infix
  Data Structures/Infix_postfix.py
Labels: LGMSOC21, 🟨 Level2

#386 Dima/sereja problem
  Data Structures/Dima-Sereja_problem.cpp
Labels: LGMSOC21, 🟨 Level2

#398 Solution for Anagram in Python
  Gfg/anagram.py
Labels: LGMSOC21, 🟩 Level1

#403 create binary_tree_from_preorder_and_inorder.cpp
  Leetcode/binary_tree_from_preorder_and_inorder.cpp
Labels: LGMSOC21, 🟨 Level2

#406 Binary tree traversal using recursion
  Data Structures/Binary_tree_traversal.cpp
Labels: LGMSOC21, 🟨 Level2

#415 Added solution of Sudoku problem in java
  Algorithms/Backtracking/SudokuBacktracking.java
Labels: LGMSOC21, 🟧 Level3

#418 Bfs traversal
  Data Structures/BFS_graph_traversal.cpp
Labels: LGMSOC21, 🟨 Level2

#424 Counting Number of Comparisons in Binary Search
  Algorithms/Searching and Sorting/BinarySearch_Comparisons_Count.cpp
Labels: LGMSOC21, 🟧 Level3

#437 Adjacent Difference Algorithm
  Algorithms/AdjacentDifference.java
Labels: LGMSOC21, 🟩 Level1

#440 Added Expedition Problem
  Codechef/Expedition(Expedi).cpp
Labels: LGMSOC21, 🟨 Level2

#444 Hashing Implementation using array
  Data Structures/Hashing_with_arrays.cpp
Labels: LGMSOC21, 🟧 Level3

#434 Added Java solution to Covid Analyzer Problem(CodeChef)
  Codechef/CovidAnalyzer.java
Labels: LGMSOC21, 🟨 Level2

#439 JAVA solution to issue 389
  Gfg/ReverseAnArray.java
Labels: LGMSOC21, 🟩 Level1

#578 Create Rabin-Karp Algo
  Algorithms/Rabin-Karp Algo
Labels: LGMSOC21, 🟧 Level3

#567 Union of sorted array in python
  Data Structures/Union of two sorted array.py
Labels: LGMSOC21, 🟩 Level1

#450 DNF (Dutch National Flag)
  Algorithms/Searching and Sorting/DNF.cpp
Labels: LGMSOC21, 🟨 Level2

#410 Issue #376
  Gfg/Trapping Rain Water.cpp
  leetcode/Search in Rotated Sorted Array.cpp
Labels: LGMSOC21, 🟩 Level1

#417 0/1 Knapsack Recursive Code
  Gfg/01 Knapsack.cpp
Labels: LGMSOC21, 🟩 Level1

#425 C solution to issue 400
  Algorithms/Searching and Sorting/Insertion Sort using Call By Reference method.c
Labels: LGMSOC21, 🟩 Level1

#392 commit
  Algorithms/stockspanprob.c
Labels: LGMSOC21, 🟩 Level1

#433 Create stock_span_problem
  Gfg/stock_span_problem
Labels: LGMSOC21, 🟨 Level2

#443 Array implementaion of stack in DATA STRUCTURES
  Data Structures/array implementation of stack.c
Labels: LGMSOC21, 🟩 Level1

#451 C solution to issue 238
  Gfg/Next Greater Element.c
Labels: LGMSOC21, 🟩 Level1

#460 added Good or Bad string.cpp
  Gfg/Good_or_Bad_String.cpp
Labels: LGMSOC21, 🟨 Level2

#465 Added the code for Wave Sort Problem
  Algorithms/Wave sort.cpp
Labels: LGMSOC21, 🟨 Level2

#452 Added Bubble sort algo in this folder
  Algorithms/Bubble Sort.cpp
Labels: LGMSOC21, 🟨 Level2

#467 added a program for concatenated words in c++
  Algorithms/contamenatedwordscpp
Labels: LGMSOC21, 🟨 Level2

#469 union find algo of disjoint set added
  Algorithms/Disjoint Set/union_find_algorithm.cpp
Labels: LGMSOC21, 🟨 Level2

#470 Sort 0s 1s 2s added
  Gfg/Sort 0s 1s 2s.cpp
Labels: LGMSOC21, 🟨 Level2

#473 next greator element
  Data Structures/nextgreatorelement.cpp
Labels: LGMSOC21, 🟩 Level1

#475 Concentric square pattern using 2D array In C Fixes #194 please merge this code
  Hackerank/concentric square pattern.c
Labels: LGMSOC21, 🟨 Level2

#497 Palindromic_Partition.py
  Algorithms/Palindromic_Partition.py
Labels: LGMSOC21, 🟩 Level1

#515 Hollow Butterfly
  Hollow Butterfly.cpp
Labels: LGMSOC21, 🟩 Level1

#572 Hollow butterfly pattern
  Codechef/hollow butterfly pattern.py
Labels: LGMSOC21, 🟩 Level1

#511 Hailstone sequence code added
  Algorithms/hailstone_sequence.cpp
Labels: LGMSOC21, 🟨 Level2

#554 Largest Sum Solution Added
  Algorithms/Dynamic Problems/Largest Sum.cpp
Labels: LGMSOC21, 🟩 Level1

#589 Counting Number Of Comparisons in Bubble Sort
  Algorithms/Searching and Sorting/BubbleSort_Comparisons_Count.cpp
Labels: LGMSOC21, 🟨 Level2

#493 added Longest_Increasing_Subsequence ( issue #231) in java
  Algorithms/Dynamic Problems/longest_increasing_subsequence.java
Labels: LGMSOC21, 🟨 Level2

#494 Solved issue number #251 for finding the occurence of the element in an array
  Gfg/count-occurence-of-an-element-in-array.c
Labels: LGMSOC21, 🟩 Level1

#523 Added Infix to Postfix conversion algorithm.
  Algorithms/infixToPostfix
Labels: LGMSOC21, 🟨 Level2

#646 Added Radix Sort
  Algorithms/Searching and Sorting/Radix_Sort.cpp
Labels: LGMSOC21, 🟨 Level2

#690 added code for Radix sort
  Algorithms/Searching and Sorting/RadixSort.java
Labels: LGMSOC21, 🟨 Level2

#644 Rainwater Trapping problem in cpp
  Leetcode/Rainwater_trapping.cpp
Labels: LGMSOC21, 🟩 Level1

#636 LCS for 3 Strings
  Codechef/LCS-3.cpp
Labels: LGMSOC21, 🟩 Level1

#635 Added DoublyLinkedList Implementation.
  Data Structures/DoublyLinkedList
Labels: LGMSOC21, 🟩 Level1

#426 Double linked list
  Data Structures/Double_linked_list.cpp
Labels: LGMSOC21, 🟩 Level1

#654 Create Jump Search
  Algorithms/Searching and Sorting/Jump Search
Labels: LGMSOC21, 🟨 Level2

#684 added Jump search.cpp
  Algorithms/Searching and Sorting/Jump_search.cpp
Labels: LGMSOC21, 🟨 Level2

#536 ADDED CODE FOR call_by_reference (issue-151)
  Algorithms/call_by_reference.cpp
Labels: LGMSOC21, 🟩 Level1

#594 Find Minimun In Rotated Search Array Leetcode Question
  Leetcode/FindMinimunInRotatedSearchArray_Leetcode.cpp
Labels: LGMSOC21, 🟩 Level1

#591 Count occurrences of an element in a sorted array.py
  Gfg/Count occurrences of an element in a sorted array.py
Labels: LGMSOC21, 🟩 Level1

#586 Allocate Minimum Number Of Pages (java)
  Gfg/AllocateMinimumNumberOfPages.java
Labels: LGMSOC21, 🟩 Level1

#662 Added Designer_PDF_Viewer.java under HackerRank
  Hackerank/Designer_PDF_Viewer.java
Labels: LGMSOC21, 🟩 Level1

#529 Added LeetCode Question Solution.
  Leetcode/Tree/SumOfNodesWithEvenValuedGrandparent.java
Labels: LGMSOC21, 🟨 Level2

#528 Solution for Concatenated Words #404 under LGM-SOC
  Miscellaneous problems/ConcatenatedWords/ConcatenatedWords.java
  Miscellaneous problems/ConcatenatedWords/Question - Concatenated Words
  Miscellaneous problems/ConcatenatedWords/concatenatedWordsTest.java
  Miscellaneous problems/Template/template.md
Labels: LGMSOC21, 🟨 Level2

#526 Added Tower of Hanoi
  Gfg/TowerOfHanoi.java
Labels: LGMSOC21, 🟩 Level1

#527 BT traversal added
  Data Structures/Tree/TreeTraversal/InOrderTraversal.java
  Data Structures/Tree/TreeTraversal/PostOrderTraversal.java
  Data Structures/Tree/TreeTraversal/PreOrderTraversal.java
Labels: LGMSOC21, 🟨 Level2

#543 Anagram in C
  Gfg/Anagaram.c
Labels: LGMSOC21, 🟨 Level2

#544 ADDED CODE FOR Dutch National Flag Algorithm.cpp (issue-148)
  Algorithms/Dutch National Flag Algorithm.cpp.cpp
Labels: LGMSOC21, 🟨 Level2

#540 ADDED CODE FOR Chinese_Remainder_Theorem (issue-147)
  Algorithms/Chinese_Remainder_Theorem.cpp
Labels: LGMSOC21, 🟨 Level2

#569 SmartPhone Codechef
  Codechef/smartphone.py
  smartphone.py
Labels: LGMSOC21, 🟨 Level2

#705 Added Smart phone problem of codechef
  Codechef/Smart Phone (ZCO14003).cpp
Labels: LGMSOC21, 🟨 Level2

#561 Intersection of two sorted array in python
  Data Structures/Intersection of two sorted array.py
Labels: LGMSOC21, 🟩 Level1

#552 Added solution for #209 and #214
  Data Structures/max-absolute-difference.cpp
  Data Structures/partition_problem.py
Labels: LGMSOC21, 🟩 Level1

#538 ADDED CODE FOR call_by_value issue-152
  Algorithms/call_by_value.cpp
Labels: LGMSOC21, 🟩 Level1

#545 ADDED CODE FOR Greedy_algorithm_to_find_minimum_number_of_coins (issu…
  Algorithms/Greedy Algorithms/Greedy_algorithm_to_find_minimum_number_of_coins.cpp
Labels: LGMSOC21, 🟨 Level2

#583 Added the java code for rotation of array by k elements
  Data Structures/Rotation_of_Array_by_Kelements.java
Labels: LGMSOC21, 🟩 Level1

#603 Sieve_of_Eratosthenes.cpp
  Data Structures/Sieve_of_Eratosthenes.cpp
Labels: LGMSOC21, 🟨 Level2

#629 Create Sieve_of_Eratosthenes.py
  Data Structures/Sieve_of_Eratosthenes.py
Labels: LGMSOC21, 🟨 Level2

#649 Create Bubble Sort in Python
  Algorithms/Searching and Sorting/Bubble Sort in Python
Labels: LGMSOC21, 🟩 Level1

#621 C code for issue 427
  Algorithms/Searching and Sorting/Bubble Sort.c
Labels: LGMSOC21, 🟩 Level1

#612 454_B_Little_Pony_and_Sort_by_Shift.cpp
  Codeforces/454_B_Little_Pony_and_Sort_by_Shift.cpp
Labels: LGMSOC21, 🟩 Level1

#655 BFS Graph Traversal
  Algorithms/Graph/BFS.java
Labels: LGMSOC21, 🟨 Level2

#660 Added solution to kth largest number
  Gfg/Kthlargestelement.py
Labels: LGMSOC21, 🟩 Level1

#645 Adding Daimond & sand glass pattern in java
  Algorithms/Daimond.java
  Algorithms/SandGlass.java
Labels: LGMSOC21, 🟩 Level1

#664 Reverse the array
  Data Structures/ReverseArray.py
Labels: LGMSOC21, 🟩 Level1

#683 Added Destroy the EMP (CHAOSEMP)
  Codechef/Destroy the EMP (CHAOSEMP).cpp
Labels: LGMSOC21, 🟨 Level2

#686 Diameter of Binary Tree added
  Gfg/Diameter of Binary Tree.cpp
Labels: LGMSOC21, 🟨 Level2

#678 Friends Pairing Problem added
  Gfg/FriendsPairingProblem.cpp
Labels: LGMSOC21, 🟩 Level1

#658 Create AdjacentDifferenceAlgo.py
  Data Structures/AdjacentDifferenceAlgo.py
Labels: LGMSOC21, 🟩 Level1

#689 Bellman Ford Algo in C
  Algorithms/Dynamic Problems/bellmanford.c
Labels: LGMSOC21, 🟨 Level2

#722 Counting Number of Comparisons in Selection Sort
  Algorithms/Searching and Sorting/InsertionSort_Comparisons_Count.cpp
  Algorithms/Searching and Sorting/SelectionSort_Comparisons_Count.cpp
Labels: LGMSOC21, 🟨 Level2

#606 cpp code for issue 400
  Algorithms/Searching and Sorting/Insertion Sort using Call By Reference method.cpp
Labels: LGMSOC21, 🟨 Level2

#647 Create Recursive Modular Exponentiation
  Algorithms/Recursive Modular Exponentiation
Labels: LGMSOC21, 🟩 Level1

#698 Longest Substring without repeating characters
  Data Structures/Longest Substring without repeating characters
Labels: LGMSOC21, 🟩 Level1

#651 water melon problem CF #521
  Codeforces/watermelon.cpp
Labels: LGMSOC21, 🟩 Level1

#733 C solution for issue 521
  Codeforces/Watermelon.c
Labels: LGMSOC21, 🟩 Level1

#203 BirthdayGift.java
  Codechef/BirthdayGift.java
Labels: LGMSOC21, 🟨 Level2

#481 finding smallest and largest number in an array in python language
  Data Structures/searching largest and smallest in array.py
Labels: LGMSOC21, 🟩 Level1

#487 Added the code for next permutation medium level question
  Leetcode/next_permutations.cpp
Labels: LGMSOC21, 🟨 Level2

#507 addedlargestareaunderstackhistogram
  Leetcode/largestareaunderhistogram.cpp
Labels: LGMSOC21, 🟨 Level2

#518 #191
  Gfg/Convert sorted Array to BST.cpp
Labels: LGMSOC21, 🟨 Level2

#541 Added Buy and Sell Stock Problem
  Leetcode/StockProblem.java
Labels: LGMSOC21, 🟨 Level2

#557 C++ code for Painting the Fence problem
  Algorithms/Dynamic Problems/Painting the Fence.cpp
Labels: LGMSOC21, 🟩 Level1

#571 Friends and Candies codeforces solution added
  Codeforces/Friends_and_Candies_Codeforces.cpp
Labels: LGMSOC21, 🟨 Level2

#577 Stack Implementation using array
  Data Structures/Stack-implementation_using_array.cpp
Labels: LGMSOC21, 🟩 Level1

#617 Hamming Distance (leetcode) #581
  Leetcode/Hamming_Distance.cpp
Labels: LGMSOC21, 🟨 Level2

#618 C code for issue 430
  Gfg/Armstrong Number.c
Labels: LGMSOC21, 🟩 Level1

#620 C++ Program to evaluate the Length of Highest Mountain
  Leetcode/Longest_Mountain_Array.cpp
Labels: LGMSOC21, 🟨 Level2

#628 C++ code for issue 435
  Codeforces/Phoenix and Puzzle.cpp
Labels: LGMSOC21, 🟨 Level2
