Repository Ayush7614/Daily-Coding-DS-ALGO-Practice, pull requests merged in 2021-05, with the labels that each got.

#48 Hackerrank Solutions Added
  Hackerank/Bit Array.cpp
  Hackerank/Box It.cpp
  Hackerank/Bubble Sort.cpp
  Hackerank/Delete-Duplicate-Value-Node-From-Sorted-LinkedList.c]
  Hackerank/Mark and Toys.py
  Hackerank/Reverse a Doubly Linked List.cpp
Labels: under-review

#46 Create Small Triangles, Large Triangles.c
  Hackerank/Small Triangles, Large Triangles.c
Labels: help wanted, under-process, under-review

#37 Create Printing Pattern Using Loops.c
  Hackerank/Printing Pattern Using Loops.c
Labels: help wanted, review, under-process, under-review

#41 Create Digit Frequency.c
  Hackerank/Digit Frequency.c
Labels: review

#39 Create Dynamic Array in C.c
  Hackerank/Dynamic Array in C.c
Labels: under-review
